name: Secret scan
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm \
            -v "$(pwd):$(pwd)" \
            -w "$(pwd)" \
            secretlint/secretlint \
            secretlint --maskSecrets '**/*'
         continue-on-error: false 